### ISSUE TITLE
Not working with phantom 1.7.0

### ISSUE THREAD

**Issue by JordanSlaman** [sheebz/phantom-proxy#5]
I may very well be doing something wrong, but I can't find what's wrong with my code, and I keep getting this error:

server running already

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<ChildProcess> has no method 'unref'
    at /home/ubuntu/node_modules/phantom-proxy/lib/proxy.js:105:28
    at /home/ubuntu/node_modules/phantom-proxy/lib/proxy.js:152:21
    at Request._callback (/home/ubuntu/node_modules/phantom-proxy/lib/proxy.js:136:36)
    at /home/ubuntu/node_modules/phantom-proxy/lib/request/main.js:122:22
    at Request.emit (events.js:67:17)
    at ClientRequest.<anonymous> (/home/ubuntu/node_modules/phantom-proxy/lib/request/main.js:224:10)
    at ClientRequest.emit (events.js:67:17)
    at Socket.<anonymous> (http.js:1210:13)
    at Socket.emit (events.js:88:20)
    at Array.0 (net.js:320:10)

It will print anything before:

phantomProxy.create({'loadImages':'no'}, function(proxy) {

but nothing after...

**Comment by sheebz** [comment]
Sounds like unref might not be on your version of node.  Could you let me know what node version you are running?  Could you paste output from running "node --v" ?

**Comment by JordanSlaman** [comment]
node --v is unrecognized.

node --version replies 'v0.6.12'

**Comment by jokeyrhyme** [comment]
Works perfectly with Node.JS 0.8.14.
